language: java
jdk:
  - openjdk11

branches:
  only:
    - master

# Travis CI 서버의 Cache 활성화
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

after_success:
  - ./mvnw jacocoTestReport coveralls