language: java
jdk:
  - openjdk11

branches:
  only:
    - master

install: true

script:
  - ./mvnw clean install
  - bash <(curl -s https://codecov.io/bash)

# Travis CI 서버의 Cache 활성화
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

after_success:
  - ./mvnw jacocoTestReport coveralls