spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/btvdb?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: tjehd2tkfkd!

mybatis:
  type-aliases-package: com.example.skbproject.dto
  mapper-locations: mappers/**/*.xml

restTemplate:
  factory:
    readTimeout: 5000
    connectTimeout: 3000
  httpClient:
    maxConnTotal: 100
    maxConnPerRoute: 5